### ISSUE TITLE
Table view of reviews

### ISSUE THREAD

**Issue by romilrobtsenkov** [kkkaur/php-ruhmatoo-projekt#3]

**Comment by kkkaur** [comment]
Information: working in grupitoo2 folder only.
I seem to have encountered a fatal error in my code.
After inserting text into critic cell and pressing enter, I get this error:
Fatal error: Call to a member function bind_param() on a non-object in /home/kaurkal/public_html/GT_Kaur_Tauno_Koit/php-ruhmatoo-projekt/grupitoo2/functions.php on line 52 
-
Probably the case is that the data (logged in user's id and text that is entered in website) I want to insert into new table is not valid somehow. 
echo $_SESSION["id_from_db"]; gives me the logged in user's id in the website, but seems that it's not valid to enter it into other table.

**Comment by kkkaur** [comment]
If I enter the code into PuTTY manually, then it inserts the data into table:
insert into test (id, critic) VALUES (1, "test"):

mysql> INSERT INTO test (id, critic) VALUES (1, "test");
Query OK, 1 row affected (0.00 sec)

**Comment by kkkaur** [comment]
Got it working (at least inserting data to table). The problem wasn't in functions.php, but in landingpage.php. 
OMG, searching and fixing errors and bugs are so cool!
Now I'm gonna rework the table and then insert functions to get data from tables to show it in top10.php webpage.

**Comment by kkkaur** [comment]
Getting data from tables and showing it in webpage is working now! Took some time, but it works. PHP is bloody awesome!
PS! Vusial side of my page is not the best, but it's rather CSS and HTML thing...
